### ISSUE TITLE
Review prescribing_exercises.ipynb

### ISSUE THREAD

**Issue by rgaiacs** [anenadic/2019-03-16-manchester#3]
I drafted the prescribing_exercises.ipynb based on the tree questions that we discussed with Andy:

- What are the BNF codes for amoxicillin showing up in data?
- What is the most commonly prescribed antibiotic?
- Which GP surgery has prescribed the most and the least antibiotics?
- Distribution of antibiotics prescribed by GP practices?

I will review this notes over the weekend.

@gcapes if you can have a look on 07414c1 on Friday will be awesome. No problem if you don't have time.

**Comment by gcapes** [comment]
It took me a while to figure out why all the spaces were needed in cell 26
 `if row["BNF NAME                                    "].lower().find("amoxicillin"):`

I don't suppose it will be immediately obvious to the students either, and having a column header with loads of spaces in, in a csv file seems rather pointless. Perhaps we would be better to modify the headers to move trailing spaces?

**Comment by rgaiacs** [comment]
> I don't suppose it will be immediately obvious to the students either, and having a column header with loads of spaces in, in a csv file seems rather pointless. Perhaps we would be better to modify the headers to move trailing spaces?

This is how is on the file that Andy sent to us. And part of the workshop is to show how to debug. I think this is a good real case.

**Comment by gcapes** [comment]
I see the data files have changed to remove the trailing white space in the column headings, but the notes haven't. I'm fixing it and will push a commit soon.
